### ISSUE TITLE
Is Not Download PDF

### ISSUE THREAD

**Issue by simrspersahabatan** [simologos/docusaurus-plugin-papersaurus#1]
Hi, It's not downloaded a pdf, it's give me a url like this

`url_domain/pdfs/name_file.pdf`

i'm hosting at vercel and give me an error.

```
Page Not Found

We could not find what you were looking for.

Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
```

this is my config

```
[
      'docusaurus-plugin-papersaurus',
      {
        keepDebugHtmls: false,
        sidebarNames: ['RSUP PERSAHABATAN'],
        rootDocIds: [
          { version: 'default', rootDocId: 'start_overview'}
        ],
        addDownloadButton: true,
        autoBuildPdfs: false,
        downloadButtonText: 'Download as PDF',
        ignoreDocs: ['licenses'],
        stylesheets: [],
        scripts: [],
        coverPageHeader: `...`,
        coverPageFooter: `...`,
        getPdfCoverPage: (siteConfig, pluginConfig, pageTitle, version) => {
          return `...`;
        },
        getPdfPageHeader: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        getPdfPageFooter: (siteConfig, pluginConfig, pageTitle) => {
          return `...`;
        },
        author: 'SIMRS DESTA',
        footerParser: /© RSUP PERSAHABATAN\d{4}-\d{2}-\d{2}Page \d* \/ \d*/g,
      },
    ],
```
may i have missing something?

**Comment by simologos** [comment]
Hi there!

Do you see the PDF's on your local file system when running yarn build?
Or could you share the console output or provide us access to the repo?

Thanks!

**Comment by simrspersahabatan** [comment]
Hi, thanks for your response.

sure you can check build at https://prima.simrspersahabatan.co.id/ which is i am using vercel for build.

[https://prima.simrspersahabatan.co.id/pdfs/pembukaan-kata-pengantar.pdf](https://prima.simrspersahabatan.co.id/pdfs/pembukaan-kata-pengantar.pdf)

as we know, we can put pdf to vercel without from github, can i change url to save pdf?

thanks before.

**Comment by techfreak01** [comment]
Hi simrspersahabatan

You didn't answer simologos question, if you find any generated PDF files in your local file system after running it.

With autoBuildPdfs set to false in your configuration, you need to manually run `docusaurus papersaurus:build` to create the PDF files after you already built the html's with `docusaurus build`.

After that, you should find an additional folder `pdfs` in the `build` folder containing the generated PDF files.

But I see some issues in your configuration:

- As described in the README.md file, the parameter `sidebarNames` doesn't currently support more than one entry, but you have two.
- Probably the value `start_overview` in parameter `rootDocIds` is not correct for you There you should add the id of your root markdown file. if you have start_overview here, the plugin assumes you have a markdown file with `id: start_overview` and `slug: /` in the header.
- The parameters getPdfCoverPage, getPdfPageHeader and getPdfPageFooter should return some html to be used as cover page, page header and page footer in the PDF files. You may use the sample code in documentation as a starting point instead of just `return '...';`

Hope that helps!

Otherwise please post the console output of `docusaurus papersaurus:build`.

Thanks!
